resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
  - repository: matching_repo
    type: github
    endpoint: ROCm
    name: ROCm/clr
    ref: $(Build.SourceBranch)
  - repository: hipother_repo
    type: github
    endpoint: ROCm
    name: ROCm/HIP # leverage HIP job that builds both AMD and NV backends
    ref: $(Build.SourceBranch)

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - amd-staging
    - amd-mainline
  paths:
    exclude:
    - '.github'
    - CODEOWNERS
    - LICENSE.txt
    - '**/*.md'

pr:
  autoCancel: true
  branches:
    include:
    - amd-staging
    - amd-mainline
  paths:
    exclude:
    - '.github'
    - CODEOWNERS
    - LICENSE.txt
    - '**/*.md'
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/HIP.yml@pipelines_repo
